services:
  mysql:
    image: mysql:8.3.0
    container_name: blogging-api-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
